package com.sefryek.brokerpro.dto.response.mobile.alert.enumeration;

/**
 * Copyright 2016 (C) sefryek.com
 *
 * @author: Amin Malekpour
 * @email: amin.malekpour@hotmail.com
 * @date: 30, Apr, 2017
 */
public enum  ConditionType {
    PRICE_CONDITIONS_TRADE_PRICE,
    PRICE_CONDITIONS_CLOSING_PRICE,
    PRICE_CONDITIONS_LOWEST_TRADE_PRICE_OF_DAY,
    PRICE_CONDITIONS_HIGHEST_TRADE_PRICE_OF_DAY,
    PRICE_CONDITIONS_LOWER_STATIC_THRESHOLD,
    PRICE_CONDITIONS_UPPER_STATIC_THRESHOLD,
    SYMBOL_CONDITIONS_TOTAL_TRADE_VALUE,
    SYMBOL_CONDITIONS_TOTAL_NUMBER_OF_SHARES_TRADED,
    SYMBOL_CONDITIONS_TOTAL_NUMBER_OF_TRADES,
    QUEUE_CONDITIONS_NUMBER_OF_ORDERS_AT_BEST_BUY,
    QUEUE_CONDITIONS_BEST_BUY_LIMIT_QUANTITY,
    QUEUE_CONDITIONS_BEST_BUY_LIMIT_PRICE,
    QUEUE_CONDITIONS_NUMBER_OF_ORDERS_AT_BEST_SELL,
    QUEUE_CONDITIONS_BEST_SELL_LIMIT_QUANTITY,
    QUEUE_CONDITIONS_BEST_SELL_LIMIT_PRICE;
}
